### ISSUE TITLE
adding 3rd party or native libraries to scripts?

### ISSUE THREAD

**Issue by AmirhosseinBidokhti** [ivision-research/burpscript#1]
Hi there, thanks for this great project. Just a question, Is there any way to add and import 3rd party libraries to the scripts that are written and imported by the extension?

**Comment by drosseau-ivision** [comment]
I primarily use this in Python, and `import X` should work. If not, I just pushed some changes to the `dev` branch that fixed a regression that I'll merge later this week once we get some other changes we want to include in the next release figured out. It will allow you to update your config file to look like:

```
{
    "python": {
        "executablePath": "/path/to/venv/bin/python3.XX",
        "pythonPath": "/path/to/venv/lib/python3.XX/site-packages:/path/to/venv/lib64/python3.XX/site-packages"
    }
}
```
and install dependencies you want into the `venv`. These changes will be reflected in the README once they're merged. Currently, the config file is only global and can't be set per project, so you'll have to update that if you want different configs for different projects, which is a bit of a pain.

Dealing with native libraries may be more finicky and is definitely uncharted territory as I've never had to do that. The polyglot API is a bit opaque sometimes, and if you need to do something complicated with a native library, it may just make sense to use `helpers.exec` or `helpers.execStdin` with an external program.

**Comment by AmirhosseinBidokhti** [comment]
Thanks for putting the time to reply. I actually used it via JavaScript; the es6 import via .mjs and 'require' worked fine with my own custom files. But importing other libraries raised error (for example, installed something via npm and imported it). 

The use case I had in my mind was some how I could add an 'http' library or 'fs' module so could push the extracted params out of the request/response and the API this tool provides to an external db.

With what you explained, I assume I can achieve that by simply creating an external service and call it via `helpers.exec` or `helpers.execStdin`.

**Comment by drosseau-ivision** [comment]
For JavaScript we currently set the `js.commonjs-require-cwd` to the script's directory. From the docs over in GraalJs [here](https://github.com/oracle/graaljs/blob/1e5c54b1e63755c9b04dc13a744001404f5bf6c0/docs/user/Modules.md?plain=1#L153) I think you should maybe be able to have a `node_modules` in that directory and import from there?

There is also the option of using one of the JavaScript bundlers to bundle everything into a single `script.js` and load that.

Side note, glad to see the JavaScript part working and being used. We're primarily a Python based team so it was kinda just tossed in as a "well why not" option.
